# NapCatQQ配置
napcat:
  # enable 默认为true, 选用napcat
  enable: true
  httpServers:
    enable: true
    host: 'http://localhost'
    port: 3000
    token: 'server_token'
  httpClients:
    enable: true
    host: 'localhost'
    port: 6001
    token: 'clients_token'

data_path : '/home/ubuntu/luo9/luo9_bot/data/'

bot_id : 1111111111
master : 1111111111

group_list : [1111111111, 1111111111]

B站直播检测推送列表 : [1111111111, 1111111111]
节日检测推送列表 : [1111111111, 1111111111]

土豆直播间ID : 987654

AI语音音色 : 'voice_type'
