# 排除一系列通常被忽略的目录
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "data",     # 忽略data目录
    "*.yaml",   # 忽略yaml配置文件
    "*.log",    # 忽略log文件
    "*.ini",    # 忽略ini文件
]

# 与 Black 保持一致
line-length = 88
indent-width = 4

# 假定使用 Python 3.10
target-version = "py310"

[lint]
# 默认启用 Pyflakes (F) 和 pycodestyle (E) 的部分规则。
# 与 Flake8 不同，Ruff 默认不启用 pycodestyle 的警告类规则 (W)
# 以及 McCabe 复杂度检查 (C901)
select = ["E4", "E7", "E9", "F"]
ignore = []

# 允许对所有启用的规则进行自动修复（当提供 --fix 参数时）
fixable = ["ALL"]
unfixable = []

# 允许以下划线前缀的未使用变量
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
# 与 Black 相同，字符串使用双引号
quote-style = "double"

# 与 Black 相同，使用空格而非制表符进行缩进
indent-style = "space"

# 与 Black 相同，保留末尾逗号
skip-magic-trailing-comma = false

# 与 Black 相同，自动检测合适的换行符格式
line-ending = "auto"

# 启用文档字符串中代码示例的自动格式化（支持 Markdown、
# reStructuredText 的代码/字面块以及 doctests）
#
# 当前默认禁用，但未来计划将此功能改为默认启用（需手动关闭）
docstring-code-format = false

# 设置格式化文档字符串内代码片段时的行长度限制
# 此配置仅在启用 docstring-code-format 时生效
docstring-code-line-length = "dynamic"