[napcat]
ws_client_host = "0.0.0.0"
ws_client_port = 7000

ws_server_host = "127.0.0.1"
ws_server_port = 3000

timeout_seconds = 10

token="token"

[logging]
level = "info"

[plugins]
enabled = true
plugin_dir = "plugins"
auto_load = true
plugins = []

[webui]
enabled = true
host = "127.0.0.1"
port = 27080